#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["SICPA_Challenge/SICPA_Challenge.csproj", "SICPA_Challenge/"]
COPY ["DAL/DAL.csproj", "DAL/"]
COPY ["BLL/BLL.csproj", "BLL/"]
RUN dotnet restore "SICPA_Challenge/SICPA_Challenge.csproj"
COPY . .
WORKDIR "/src/SICPA_Challenge"
RUN dotnet build "SICPA_Challenge.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SICPA_Challenge.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SICPA_Challenge.dll"]